title: <p align="center">Manish Ranjan</p>
logo: /assets/img/manish.png
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/ranjanmanish/">LinkedIn</a> |
  <a href="https://github.com/bappa-2000">GitHub</a>
  
  <br>   
    Technical and Business leader, served medium to large scale clients globally in the last 22 years of experience in diversified domains, primarily in Media & Entertainment, e-Commerce, Sports and Business Intelligence. Proven success in leading profiles like Project Delivery, Program Management, Account Management and Project Management.
  <br>
  </p>
